<?php
/**
 * Extend Warranty - Bundled product warranty offers block, offer by purchase price
 *
 * @author      Extend Magento Team <magento@extend.com>
 * @category    Extend
 * @package     Extend_Warranty
 * @copyright   Copyright (c) 2022 Extend Inc. (https://www.extend.com/)
 */
/**
 * @var \Magento\Catalog\Block\Product\View $block
 */

/** @var \Extend\Warranty\ViewModel\Warranty $viewModel */
$viewModel = $block->getData('viewModel');
/** @var string $offerTypeArea */
$offerTypeArea = $block->getData('offerTypeArea');
/** @var \Magento\Catalog\Model\Product $product */
$product = $block->getProduct();
?>
<?php if ($viewModel->isExtendEnabled()): ?>
    <?php $placement = $viewModel->getProductDetailPageOffersPlacement(false); ?>
    <script type="text/x-magento-init">
    {
        "#product_addtocart_form .box-tocart": {
            "bundleProductWarranty": {
                "isInProductView": true,
                "productId": "<?= $block->escapeJs($product->getId()) ?>",
                "productSku": "<?= $block->escapeJs($product->getSku()) ?>",
                "productInfo": <?= json_encode($viewModel->getProductInfo($product)); ?>,
                "buttonEnabled": <?= $block->escapeJs($viewModel->isProductDetailPageOffersEnabled() ? 1 : 0) ?>,
                "modalEnabled": <?= $block->escapeJs($viewModel->isInterstitialCartOffersEnabled() ? 1 : 0) ?>,
                "insertionPoint": "<?= $block->escapeJs($placement['insertionPoint']) ?>",
                "insertionLogic": "<?= $block->escapeJs($placement['insertionLogic']) ?>"
            }
        }
    }
    </script>
<?php endif; ?>
